from fpdf import FPDF
from datetime import datetime
import matplotlib.pyplot as plt
import os

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, '📊 Business Insight Report', ln=True, align='C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align='C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by Shubham Mishra | Confidential', 0, 0, 'C')

def generate_pdf(insights_list, df, filename="Business_Insights_Report.pdf"):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # 🧠 Insights Section
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "🧠 Smart Insights", ln=True)
    pdf.set_font("Arial", '', 11)
    for insight in insights_list:
        pdf.multi_cell(0, 8, f"• {insight}")

    pdf.ln(5)

    # 📈 Embed Sample Graphs (max 2)
    numeric_cols = df.select_dtypes(include='number').columns.tolist()
    if numeric_cols:
        for col in numeric_cols[:2]:  # Limit to first 2 charts
            plt.figure(figsize=(5, 3))
            df[col].dropna().hist(color='skyblue', edgecolor='black')
            plt.title(f"Distribution of {col}")
            plt.xlabel(col)
            plt.ylabel("Count")
            img_path = f"{col}_plot.png"
            plt.tight_layout()
            plt.savefig(img_path)
            plt.close()

            pdf.add_page()
            pdf.set_font("Arial", 'B', 12)
            pdf.cell(0, 10, f"📈 {col} Distribution Chart", ln=True)
            pdf.image(img_path, w=180)
            os.remove(img_path)

    pdf.output(filename)
    return filename

